SET( CPACK_PACKAGE_CONTACT "Andreas Grob <vilarion@illarion.org>" )
set( CPACK_PACKAGE_VENDOR "Illarion e.V." )
set( CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/COPYING" )
set( CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.txt" )

set( CPACK_DEBIAN_PACKAGE_GENERATE_SHLIBS ON )
set( CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON )

set( CPACK_DEBIAN_PACKAGE_PRIORITY standard )
set( CPACK_DEBIAN_PACKAGE_SECTION games )
set( CPACK_DEBIAN_COMPRESSION_TYPE xz )

set( CPACK_DEBIAN_FILE_NAME DEB-DEFAULT )

if( CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo" )
  set( CPACK_DEBIAN_DEBUGINFO_PACKAGE ON )
endif()
