version: "3.8"

services:
  game-server:
    build:
      context: .
      args:
        VARIANT: bullseye
    depends_on:
      db:
        condition: service_healthy
    environment:
      ILLARION_REUSE_LINTER_CONTAINER: ${REUSE_LINTER_CONTAINER}
    init: true
    volumes:
      - type: bind
        source: ${SCRIPT_PATH}
        target: /scripts
        read_only: true
      - type: bind
        source: ${MAP_PATH}
        target: /maps
        read_only: true
      - type: volume
        source: pg-socket
        target: /var/run/postgresql
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
      - type: volume
        source: build-dir
        target: /tmp/illarion/build
      - type: volume
        source: vscode-dir
        target: /tmp/vscode
    ports:
      - "${SERVER_PORT}:3012"
    
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    # Enable support for ptrace based debuggers
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    
  db:
    image: ghcr.io/illarion-ev/illarion-dev-postgres
    restart: unless-stopped
    volumes:
      - type: volume
        source: local-db
        target: /var/lib/postgresql/data
      - type: volume
        source: pg-socket
        target: /var/run/postgresql
    environment:
      POSTGRES_USER: illarion
      POSTGRES_PASSWORD: illarion
      POSTGRES_DB: illarion
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U illarion"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          memory: 20M
      
volumes:
  local-db:
  pg-socket:
  build-dir:
  vscode-dir: