version: "3.8"

services:

  clang-tidy:
    image: ghcr.io/illarion-ev/illarion-server-tools-clang
    volumes:
      - type: bind
        source: ..
        target: /src

    command: sh -c "run-clang-tidy.sh"
