version: "3.8"

services:

  clang-tidy:
    image: ghcr.io/illarion-ev/illarion-server-tools-clang:sha-b185f1e1
    volumes:
      - type: bind
        source: ..
        target: /src

    command: sh -c "run-clang-tidy.sh"
