version: "3.8"

services:

  clang-tidy:
    image: ghcr.io/illarion-ev/illarion-server-tools-clang
    volumes:
      - type: bind
        source: ..
        target: /src
      - type: volume
        source: build
        target: /build

    command: sh -c "run-clang-tidy.sh"

volumes:
  build:
