version: "3.8"

services:

  cppcheck:
    image: ghcr.io/illarion-ev/illarion-server-tools-cppcheck:sha-94c41a15
    volumes:
      - type: bind
        source: ..
        target: /src
    network_mode: none
