name: Code Review

on:
  push:
    branches:
      - master
      - develop

  # Run tests for any PRs.
  pull_request:

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run cppcheck
        run: tools/run-cppcheck

  clang-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run clang-format
        run: tools/run-clang-format && git diff --exit-code
